### ISSUE TITLE
Parcel not found

### ISSUE THREAD

**Issue by pansylee** [brandiqa/docker-node#2]
Initial error with es-abstract at 1.14.0, googling said 1.14.0 got bumped and to use 1.14.2 - changing to 1.14.2 in package.json seemed to get past issue.  Now getting parcel : not found.  Added hot module reloading 1235 & parcel 1234 port forwarding rules.  Guessing devDependencies..."parcel-bundler": "^1.12.3" in your package.json is suppose to install parcel?  Log:

dev_1  | > parcel src/index.html --hmr-port 1235
dev_1  |
dev_1  | sh: 1: parcel: not found
dev_1  | npm ERR! code ELIFECYCLE
dev_1  | npm ERR! syscall spawn
dev_1  | npm ERR! file sh
dev_1  | npm ERR! errno ENOENT
dev_1  | npm ERR! website@1.0.0 start: `parcel src/index.html --hmr-port 1235`

Just starting to learn about web apps and some basic docker knowledge and not familiar with make...

**Comment by brandiqa** [comment]
Did you add your workspace folder to your Share Folder settings in Virtual Box? Also can you provide the command you used when you encountered this error.

**Comment by brandiqa** [comment]
The issue with parcel dependencies is fixed now. I've updated all the packages.
