### ISSUE TITLE
es-abstract@1.14.0 not found

### ISSUE THREAD

**Issue by gmdavef** [brandiqa/docker-node#4]
Michael, thanks for your article at https://www.sitepoint.com/docker-windows-10-home/. 
Ran the make command, but getting an error that es-abstract@1.14.0 is not found on npm registry.  Do you know how I can resolve?  Thank you

$ make
docker volume create nodemodules
nodemodules
docker-compose -f docker-compose.builder.yml run --rm install
Creating network "website_default" with the default driver
Pulling install (node:10-jessie-slim)...
10-jessie-slim: Pulling from library/node
Digest: sha256:75f4c81c4aa49c71c2a46c023f8e206b6bce0546991a8289493940aa23aeb72f
Status: Downloaded newer image for node:10-jessie-slim
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/postcss-8161ca8d/package.json'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/source-map-197a2f25/package.json'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/postcss-8161ca8d/README.md'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/source-map-197a2f25/README.md'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/postcss-8161ca8d/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/csso-633e7cf4/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/postcss-8161ca8d/CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/csso-633e7cf4/README.md'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/postcss-679fc72b/lib/css-syntax-error.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/source-map-support-d86dbe24/LICENSE.md'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/source-map-support-d86dbe24/README.md'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/postcss-679fc72b/lib/declaration.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/postcss-679fc72b/lib/input.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/react-dom-dc75432f/umd/react-dom.profiling.min.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/source-map-30a74b42/dist/source-map.min.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/postcss-c0fd84e8/lib/list.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/postcss-23784974/lib/list.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/postcss-679fc72b/lib/lazy-result.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/postcss-c0fd84e8/lib/map-generator.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/postcss-23784974/lib/map-generator.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/node/ClassSelector.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/terser-3b043e61/tools/colorless-console.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/terser-f0e04d46/dist/bundle.js.map'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/terser-3b043e61/tools/domprops.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/node/Combinator.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/node/Comment.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/node/Declaration.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/node/DeclarationList.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/scope/default.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/node/Dimension.js'
npm WARN tar ENOENT: no such file or directory, lstat '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/pseudo'
npm WARN tar ENOENT: no such file or directory, lstat '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/function'
npm WARN tar ENOENT: no such file or directory, lstat '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/function'
npm WARN tar ENOENT: no such file or directory, lstat '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/atrule'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/node/Function.js'
npm WARN tar ENOENT: no such file or directory, lstat '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/pseudo'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/node/HexColor.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/node/Identifier.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/node/IdSelector.js'
npm WARN tar ENOENT: no such file or directory, lstat '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/atrule'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/convertor/index.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/generator/index.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/lexer/grammar/index.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/lexer/index.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/parser/index.js'
npm WARN tar ENOENT: no such file or directory, lstat '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/atrule'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/index.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/node/index.js'
npm WARN tar ENOENT: no such file or directory, lstat '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/pseudo'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/syntax/scope/index.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/src/app/node_modules/.staging/css-tree-80b7f321/lib/tokenizer/index.js'
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/es-abstract/-/es-abstract-1.14.0.tgz
npm ERR! 404
npm ERR! 404  'es-abstract@1.14.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'app'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-11T22_33_07_756Z-debug.log
make: *** [Makefile:6: install] Error 1

**Comment by brandiqa** [comment]
Hi Dave,

Thanks for checking out my article. The error you are getting means the npm
install command did not complete or the node_modules folder was not mounted
properly. Are the scripts you are using exactly as they are in the
repository?

If so, try deleting the image that was built earlier and run again. You can
also change Node.js image to `node:slim` and see if that will resolve the
issue.

Let me know how it goes.

Kind regards,
Michael

**Comment by eunnovax** [comment]
Hello Michael,

1. I have deleted an image, then tried again and still the same error appears.
2. Then I have changed Node image to 'node:slim', and it didn't resolve the issue as well.

What could be the reason why node_modules is not being mounted properly?

**Comment by eunnovax** [comment]
Ok Michael, I've solved the issue by installing newer version of es-abstract.
 'npm i es-abstract@1.14.2'

**Comment by brandiqa** [comment]
Sorry for the late response. I've updated all the packages.  Currently working on the mounting issue

**Comment by brandiqa** [comment]
I've updated instructions for the mounting issues in README.md. In VirtualBox shared folder settings, please **prefix** a `/c` or `/d/` depending on the partition in the mount path settings. Please look at the screenshots I've placed in [README](https://github.com/brandiqa/docker-node/blob/master/README.md) that clarifies this part. Will update the main article soon.Feel free to create a new ISSUE if the problem still persists.
